on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup Python and create a virtual environment
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install remarshal

      - uses: LOWPROKB/zmk/.github/workflows/build-user-config.yml@corne-ish-zen-v2
