on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install remarshal
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install remarshal

      - name: Run build workflow
        uses: LOWPROKB/zmk/.github/workflows/build-user-config.yml@corne-ish-zen-v2
