on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04  # Force Ubuntu 22.04
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install remarshal
      
      # This reusable workflow section should stay separate
  build-reusable:
    uses: LOWPROKB/zmk/.github/workflows/build-user-config.yml@corne-ish-zen-v2
