on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: LOWPROKB/zmk/.github/workflows/build-user-config.yml@corne-ish-zen-v2

  setup-python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
