on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: LOWPROKB/zmk/.github/workflows/build-user-config.yml@corne-ish-zen-v2

    # Add Python setup here, but outside of the reusable workflow
    pre-steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
